### PR TITLE
Remove reference to missing theme image file

### PR DESCRIPTION
**Pull request by brlogan**
One of the image files for the "Fil" query-theme is missing: ui-bg_highlight-soft_75_d7d5c0_1x100.png
Changing the "background" property to just use the color.

### CODE REVIEW

**Comment by apolkosnik** [comment]
Looks good

**Comment by mgoffin** [comment]
All of the other themes use this:

`background: url('/new_images/top_bar_bg.png') repeat-x;`

Just curious why this isn't the fix here?

**Comment by brlogan** [comment]
I figured that Fil intentionally chose a different color than the one that is provided by top_bar_bg.png

**Comment by mgoffin** [comment]
I just tried changing to the Fil theme and even after clearing browser cache it didn't look very different, haha. Does adding the line above make things look weird or still fine?

**Comment by brlogan** [comment]
It makes the top and bottom bars a tan color for me.

**Comment by mgoffin** [comment]
I guess it's fine then. If there's an issue at least we can look back at this and see what the other themes do.

**Pull request merged**
