### PR TITLE
Add Description field for Sample upload forms

### PR DESCRIPTION
**Pull request by frbapolkosnik**
It includes the single sample, and bulk sample uploads.

### CODE REVIEW

**Comment by frbapolkosnik** [comment]
Some basic testing done

**Comment by gbartz** [comment]
-----Original Message-----

**Comment by frbapolkosnik** [comment]
Gbartz, What are you saying? injection works? Bulk upload?

**Comment by gbartz** [comment]
Disregard.

**Comment by mgoffin** [comment]
Add Related PR was accepted, so this will need some fixing up where there are conflicts.

**Comment by frbapolkosnik** [comment]
Donezo!

**Comment by mgoffin** [comment]
Doesn't seem to handle the situation where there's already a description. Looks like it overwrites it completely?

**Comment by frbapolkosnik** [comment]
handle_file() is doing things properly

**Comment by frbapolkosnik** [comment]
Is this acceptable?

**Comment by mgoffin** [comment]
It can't be merged automatically so it will need some merging with existing master. Then I'll give it a try and proceed accordingly!

**Comment by frbapolkosnik** [comment]
The merge conflicts have been resolved.

**Pull request merged**
