### PR TITLE
Wrapped template loaders in cached.Loader and added some nice debug toolbars

### PR DESCRIPTION
**Pull request by apolkosnik**
- Wrapped template loaders in cached.Loader  (https://docs.djangoproject.com/en/dev/ref/templates/api/#django.template.loaders.cached.Loader)
- Added some nice debug toolbars

### CODE REVIEW

**Comment by apolkosnik** [comment]
debug toolbars only show up when DEBUG=True

**Comment by apolkosnik** [comment]
Caching automatically turns off when DEBUG=True

**Comment by mgoffin** [comment]
Let me know when you think you're all set with adding toolbar features :)

**Comment by apolkosnik** [comment]
I think that it's enough for now

**Pull request merged**
