### PR TITLE
Couple of small changes to make Screenshots more usable.

### PR DESCRIPTION
**Pull request by apolkosnik-old**
At first, I've added the same kinds of changes that I made for raw_data in order to propagate source from the parent sample. 

Then I added timestamp for the embedded source creation. 

I also changed s.save() to s.save(username=analyst)
and added two calls to .reload() after data is saved.

Please take a look and comment if you'd feel that I'm doing something the wrong way.

Thanks!

### CODE REVIEW

**Comment by mgoffin** [comment]
When adding a screenshot to a TLO it does not inherit the sources which I would expect to be the behavior since you're noting that it will propagate sources from the parent.

**Comment by frbapolkosnik** [comment]
@mgoffin do you need that for the AddScreenshot part in the UI when adding the screenshots by hand or just take the embeddedSource from the TLO and shove it into the Screenshot?

**Comment by mgoffin** [comment]
Given that a screenshot can be associated with multiple TLOs, you'd have to merge any duplicate sources so all of the instances stack up properly as well as add any new sources?

**Comment by frbapolkosnik** [comment]
I'll have to come up with a few test cases for this.

**Comment by apolkosnik-old** [comment]
This is no longer needed after #896, since it was almost the same thing.

**Pull request closed without merging**
