### PR TITLE
Updated handling of embedded sources to resemble what's happening in sam...

### PR DESCRIPTION
**Pull request by frbapolkosnik**
Updated handling of embedded sources in Raw Data to resemble what's happening in the handler for samples.

 handle_raw_data_file() in raw_data/handlers.py is not handling embedded_source objects.
I found that case when I was trying to add a text file produced by a tool that processed some sample data.

Calling hanfle_raw_data_file() with source derived from the sample (obj.source) would not work, and I'd get an object inthe database that nobody can ever see...

 res = handle_raw_data_file(data, self.obj.source, self.current_task.username,
                        title="Some Title", data_type='text',
                        tool_name='Tool name', tool_version='0.6', tool_details='http://www.nowrap.de/flare.html',
                        method=self.name,
                        copy_rels=True)

I was able to get a single source by either using a hardcoded string or by using self.obj.source[0].name

 res = handle_raw_data_file(data, self.obj.source[0].name, self.current_task.username,
                        title="Some Title", data_type='text',
                        tool_name='Tool name', tool_version='0.6', tool_details='http://www.nowrap.de/flare.html',
                        method=self.name,
                        copy_rels=True)

Then I looked into the handler for sample files, and I tried to replicate the same behavior, and now it all works with my service.

### CODE REVIEW

**Comment by mgoffin** [comment]
We *really* need more descriptive content instead of things like "....ples." For people wanting to get an overview of what's going on without having to dig through code it helps a ton. I know I've pinged you on this before so I'm hoping in the future we'll get some more properly detailed PRs :)

Also, please try to write better commit messages (https://github.com/crits/crits/wiki/Developer-Guide#writing-great-git-commit-messages).

**Comment by frbapolkosnik** [comment]
ok, updated the description. I will push the updated unswf_service next

**Comment by frbapolkosnik** [comment]
Updated handling of embedded sources in Raw Data to resemble what's happening in the handler for samples.

 handle_raw_data_file() in raw_data/handlers.py is not handling embedded_source objects.
I found that case when I was trying to add a text file produced by a tool that processed some sample data.

Calling hanfle_raw_data_file() with source derived from the sample (obj.source) would not work, and I'd get an object inthe database that nobody can ever see...

 res = handle_raw_data_file(data, self.obj.source, self.current_task.username,
                        title="Some Title", data_type='text',
                        tool_name='Tool name', tool_version='0.6', tool_details='http://www.nowrap.de/flare.html',
                        method=self.name,
                        copy_rels=True)

I was able to get a single source by either using a hardcoded string or by using self.obj.source[0].name

 res = handle_raw_data_file(data, self.obj.source[0].name, self.current_task.username,
                        title="Some Title", data_type='text',
                        tool_name='Tool name', tool_version='0.6', tool_details='http://www.nowrap.de/flare.html',
                        method=self.name,
                        copy_rels=True)


Then I looked into the handler for sample files, and I tried to replicate the same behavior, and now it all works with my service.

**Comment by frbapolkosnik** [comment]
I'm just going to remove this for now, as I had this on my master branch.

**Pull request closed without merging**
