### PR TITLE
Domain and IP Add

### LINKED ISSUE #394: Domain bulk upload add IP Broken
There seems to be a issue with bulk uploading domains with associating IP. Bulk upload domain page table validates fine. Once uploaded status message says upload complete, when checking the domain testing.com has been uploaded but the IP has not been uploaded. 
crits.log records no errors. 
Apache error log:
Traceback (most recent call last):
File "/data/crits/crits/core/handsontable_tools.py", line 221, in parse_bulk_upload (result, errors, retVal) = add_new_function(data, rowData, request, errors, is_validate_only, cache)
File "/data/crits/crits/domains/handlers.py", line 249, in add_new_domain_via_bulk is_validate_only=is_validate_only, cache=cache)
File "/data/crits/crits/domains/handlers.py", line 343, in add_new_domain cache=cache)
File "/data/crits/crits/ips/handlers.py", line 360, in ip_add_update if "Address - ipv4" in ip_type:
typeError: argument of type 'NoneType' is not iterable

### PR DESCRIPTION
**Pull request by thelok**
Fixes #394

### CODE REVIEW

**Comment by packet-rat** [comment]
Does this fix issues where Type is not populated when importing STIX packages via "Standards" and "TAXII"?

**Comment by thelok** [comment]
I very rarely ever use the STIX import. Do you have a basic STIX file where this occurs? Or what is the specific error message?

**Comment by craigh6247** [comment]
From my test of this fix, It works perfectly for Single domain upload, gives the drop down IP type on the bulk domain upload validates, then doesn't add the entries to the database, (both domains and IPs)

**Comment by thelok** [comment]
The bulk upload is working for me, you're doing "Validate Table" and then "Upload Table"? Are you seeing an error on the server side?

**Comment by craigh6247** [comment]
Table validation works fine, gives the all clear to upload, Apache error log:
Traceback (most recent call last):
File "/data/crits/crits/core/handsontable_tools.py", line 212, in parse_bulk_upload bound_form = parse_row_function(request, rowData, cache);
File "/data/crits/crits/domains/handlers.py", line 735, in parse_row_to_bound_domain_form ip.type = rowData.get(form_consts.Domain.IP_TYPE, "")
AttributeError: 'unicode' object has no attribute 'type'
mod_wsgi (pid=9259): Exception occurred processing WSGI script '/data/crits/django.wsgi'., referer: https://IP/indicators/list/

**Comment by thelok** [comment]
There is an inconsistency with your code base with the changes that were made in this fix. Line 735 you have:

```
ip.type = rowData.get(form_consts.Domain.IP_TYPE, "")
```

but the actual code change made was:

```
ip_type = rowData.get(form_consts.Domain.IP_TYPE, "")
```

https://github.com/crits/crits/pull/397/files#diff-fb745186b3a8cd7940f282f9fd4257d6R735

**Comment by brlogan** [comment]
I believe line 375 in crits/domains/handlers.py also needs to be modified to use the provided IP_TYPE.

**Comment by wxsBSD** [comment]
I'm about to push this along with the change mentioned by @brlogan. I did notice that when trying to add a domain with an associated IP address the form does not validate if I select "Address - cidr" as the IP type. I vaguely recall this being a known issue, but I'm punting on it for now.

**Comment by brlogan** [comment]
I have a PR that I'll hopefully be submitting by the end of the week that, among other things, should fix the "Address - cidr" issue.

**Pull request merged**
