### PR TITLE
Fixed edit items dialog

### PR DESCRIPTION
**Pull request by carterchurch**
Added add_new_action back into base_context; This must stay in base_context until the config page is modified to load forms from the dialog function.

### CODE REVIEW

**Comment by mgoffin** [comment]
Would it be better to fix the config page instead?

**Comment by mgoffin** [comment]
For sure. I suspect we can do the right long-term fix instead. I’m not positive but I suspect the amount of people on Master is a lot lower than stable and can probably hold out for the right fix.

**Comment by apolkosnik** [comment]
I thought that both were affected.

**Comment by carterchurch** [comment]
@mgoffin In that case, I'll close this out and look implementing this correctly

**Pull request closed without merging**
