### PR TITLE
Replacing m2crypto with pycrypto

### PR DESCRIPTION
**Pull request by frbapolkosnik**
I don't use totp, so I need somebody to test it.

### CODE REVIEW

**Comment by frbapolkosnik** [comment]
Just a quick example taken from 
http://crypto.stackexchange.com/questions/24050/why-dont-pycrypto-and-m2crypto-produce-the-same-result-as-openssl-here-aes-128

```
from Crypto.Cipher import AES
key = b'YELLOW SUBMARINE'
cipher = AES.new(key, AES.MODE_ECB, "")
msg =  cipher.encrypt(b'0123456789abcdef0123456789abcdef')
repr(msg)
```

```
import M2Crypto
cipher=M2Crypto.EVP.Cipher('aes_128_ecb',b'YELLOW SUBMARINE',"", op=1,
padding=0, salt=None)
out=b''
plaintext=b'0123456789abcdef0123456789abcdef'
out=out+cipher.update(plaintext)
repr(out)
```

**Comment by frbapolkosnik** [comment]
I can try to re-implement this with Cryptography (https://cryptography.io/en/latest/) if that's a better option for redoing the taxii_service.

On the services side, the taxii_service is the only one that used M2Crypto.

**Comment by frbapolkosnik** [comment]
The reason for this is that M2Crypto doesn't seem to be moving anywhere (Support for Python 3.x is not there, and we're having issues building it through pip).

**Comment by wzod** [comment]
FWIW I ran into a similar issue with building M2Crypto using pip just recently (had not observed that issue before).  I was able to successfully resolve the issue using python-m2crypto, and so far no significant issues.

Above suggestion might be a short-term fix as switching to pycrypto makes more sense.  I'm currently not using totp, but I will certainly test as soon as I have some cycles.

**Comment by frbapolkosnik** [comment]
In CRITs core this is the only spot (TOTP) where m2crypto is used. I think it was said that TOTP is optional, but still the m2crypto is a requirement... Since the taxii was split out as a service, there is no need to keep m2crypto as a requirement. In CRITs services the only service that uses m2crypto is taxii_service. I suppose that since m2crypto has issues building, this is a sensible workaround to get the core usable by removing this dependency. I'll add an entry for UPDATING if I'll more people think this is a good idea.

**Comment by frbapolkosnik** [comment]
After some more looking around I've decided that I'll close this PR and create a new one that uses cryptography module instead. With that It'll be much easier to migrate TAXII_service too.

**Pull request closed without merging**
