### PR TITLE
Default method/reference parameters to empty string

### PR DESCRIPTION
**Pull request by brlogan**
Some functions define the default of their Source Method and Reference fields to None instead of empty string (''). This sometimes leads to those fields being populated in CRITs with the actual text "None". However, if the data is pulled from an upload form, the field is populated with an empty string. It would be better, and more consistent, for these fields to simply be left blank if no data is provided, so we don't end up with some blank fields and some None fields.

Anybody see a problem with this?

### CODE REVIEW

**Comment by brlogan** [comment]
Any additional thoughts on this? We've been using this change in Production for awhile now and have been happy with it.

**Comment by mgoffin** [comment]
Can you give this a merge and I'll give it another test?

**Comment by brlogan** [comment]
Okay! Freshly merged.
I had to disable the CSRF middleware to test because I was getting 403s every time I tried a POST.

**Comment by mgoffin** [comment]
Evidently it needs another merge after accepting your other stuff, haha.

**Comment by brlogan** [comment]
Haha, of course it does. Give it another try, please.

**Pull request merged**
