### PR TITLE
Support STIX documents with inline embedding

### PR DESCRIPTION
**Pull request by RichieB2B**
I used a STIX export from https://github.com/MISP/MISP to develop and test this patch.

This is work in progress and needs testing to see if a fully related STIX documents still imports ok.

Also, the use of parse_observables() vs make_crits_object() needs to be more intelligent. Now both are done which can't be good.

### CODE REVIEW

**Comment by mgoffin** [comment]
Based on the discussions on the development list and the active development work going on, I am hesitant to accept any code related to CybOX/STIX as all of the code is being ripped out of core and being moved into the TAXII service.

**Comment by RichieB2B** [comment]
As long as the new code will support inline STIX documents that is fine with me. ;-)

I needed this patch to connect MISP to CRITS.

**Comment by mgoffin** [comment]
No clue. I don't plan on making the code any better. I'll leave that up to people who plan on using it. My goal is simply separating.

**Comment by RichieB2B** [comment]
I'll submit a new patch if it is not the case (and we're still using MISP and CRITS together).

**Pull request closed without merging**
