### PR TITLE
Fix the CSRF for toast notifications

### PR DESCRIPTION
**Pull request by frbapolkosnik**

### CODE REVIEW

**Comment by thelok** [comment]
+1, Thanks

**Comment by mgoffin** [comment]
Why do we need this here when we have this?

https://github.com/crits/crits/blob/master/crits/core/static/js/core.js#L649

**Comment by mgoffin** [comment]
The other function also exists in core right under the last function.

**Comment by frbapolkosnik** [comment]
I have to apologize, it looks like the whole issue was due to some stale cached javascript.

**Pull request closed without merging**
