### PR TITLE
Remove salt as provisioner.

### PR DESCRIPTION
**Pull request by gtback**
Switch to reusing as much of the bootstrap script as possible. Some
interactive options (which don't play nicely with Vagrant's shell
provisioner) are converted to Fabric tasks.

### CODE REVIEW

**Comment by gtback** [comment]
I did this to simplify the provisioning process and make it easier for development environments to stay in sync with changes to dependencies, etc. as specified in the bootstrap script. 

If there are still people using the salt provisioning process, I can probably find a way to accommodate both alternatives as provisioners.

If this is accepted, I will update the corresponding wiki page to include new, simpler directions. https://github.com/crits/crits/wiki/CRITs-Vagrant-Guide

**Comment by mgoffin** [comment]
This seems a *ton* simpler and I agree with your reasoning for doing this.

**Comment by gtback** [comment]
:smile: Thanks, @mgoffin !

**Comment by packet-rat** [comment]
@Greg: Leveraging as much of "core" as possible seems like a great idea.  

Can we twist your arm to sort out how to auto-provision Services and their dependencies?  Willing to help in the upkeep once a framework is established.  

Patrick Maroney
Cell: (609)841-5104


On Aug 18, 2015, at 5:43 PM, Greg Back <notifications@github.com> wrote:

I did this to simplify the provisioning process and make it easier for development environments to stay in sync with changes to dependencies, etc. as specified in the bootstrap script.

If there are still people using the salt provisioning process, I can probably find a way to accommodate both alternatives as provisioners.

If this is accepted, I will update the corresponding wiki page to include new, simpler directions. https://github.com/crits/crits/wiki/CRITs-Vagrant-Guide

**Comment by gtback** [comment]
I just finished updating the Wiki page. Hopefully the instructions there are clear.

@packet-rat: I need to think more about how to automatically set up CRITs services. It's a bit challenging because they are in a separate repository. It will likely be some combination of Git submodules and Vagrant synced folders, but there are drawbacks to that approach. A somewhat-sane short-term approach is to just `vagrant ssh` to the machine and install services directly.

**Comment by dicato** [comment]
@gtback Git submodules work, but generally cause frustration since when they change you need to communicate to everyone to init/update accordingly.

I wonder if additional fabric tasks would make sense to install services?

**Comment by packet-rat** [comment]
I'm ready to engage and support such an effort. Can't lead as I'm not sufficiently versed in all of the underlying moving parts.  However, more than willing to invest time in improved auto-provisioning options.

 I can typically get a brand new CRITs Dev/Test instantiation up in ~15-30 minutes from scratch using Vagrant, but then still have to spend hours manually getting all of the interrelated dependencies for the dependencies within CRITs services sorted out each time I build a system.  ChopShop an Yara seem to give me the greatest grief with issues at each step of their respective installation.  My notes are getting pretty good but it seems like a new set of issues pop-up each time.  Just as an aside, i'm typically building/testing all available CRITs Services, so this may not  be as much of an issues for others.

In any scenario, willing  to test, debug, and develop.

Patrick Maroney
Cell: (609)841-5104


On Aug 20, 2015, at 11:56 AM, Greg Back <notifications@github.com> wrote:

I just finished updating the Wiki page. Hopefully the instructions there are clear.

@packet-rat: I need to think more about how to automatically set up CRITs services. It's a bit challenging because they are in a separate repository. It will likely be some combination of Git submodules and Vagrant synced folders, but there are drawbacks to that approach. A somewhat-sane short-term approach is to just vagrant ssh to the machine and install services directly.

**Comment by gtback** [comment]
@packet-rat This conversation should probably get moved to a new issue. :smile:

**Pull request merged**
