### PR TITLE
Remove CybOX/STIX

### PR DESCRIPTION
**Pull request by mgoffin**
This PR removes CybOX/STIX as requirements for core. This has a lot of fallout which resulted in the following major changes:

- New vocabulary directory with custom CRITs vocabulary (some of it is similar to or the same as what was used with the standards because the values made sense, but we are considering them de-coupled from the standard and thus can be modified as the community sees fit).
  - These vocabularies are built on classes so there's no database lookups for these. Extending the vocabulary is as simple as adding attributes to a class and handling merge conflicts (however it's highly recommended you just open an issue for the new vocabulary value you wish to add so it can be discussed and added normally if it makes sense).
- * Downloading TLOs are back to JSON instead of STIX.
- * STIX Import is gone
- If you wish to upload a file as an Object, you can use the new "File Upload" Object type.
- If an Object cannot be made into an Indicator because its type isn't a valid Indicator type, the UI will tell you.
- Indicators needed better context, so along with the new Indicator Type vocabulary they gained a "Threat Type" field, "Attack Type" field, and vocabulary for each.
- * The "Standards API" is gone.
- The "Objects" and "Relationships" POST APIs are gone as they are no longer based on database entries.
  - To compensate, `forge_relationship` and `add_object` were exposed to the API as PATCH requests and Updating through the API is now documented.
- `forge_relationship` and `add_object` handlers have changes in arguments.

- (*) These features have been moved over to the TAXII service. Support for CybOX/STIX will stay in the TAXII service itself as the best and primary use of the standards for CRITs is through sharing which is what the TAXII service is for.

In order to properly use this PR you'll also need to use the "add_cybox_stix" branch of `crits_services` which will also have its own PR.

EDIT: I should note that there are no migrations for this PR. I intentionally left is so that people who have existing Indicator values can decide what they'd like to do. If they wish to keep those values in the database they can do so. If they want to change them all to be the same as the new vocabulary they can do that too. I was going to write a script to help but it wound up being more complicated than the simple one-liner database update command to change one thing to another.

### CODE REVIEW

**Comment by DukeOfHazard** [comment]
When attempting to add an "IPv4 address" indicator, I get an "Invalid IP type" message.

**Comment by mgoffin** [comment]
Was it a valid IPv4 address? I didn't change the validation logic but it could also not be firing it properly (or is and you gave it a bad value).

**Comment by DukeOfHazard** [comment]
I'm definitely using valid IP's.  

It looks like the problem might be in the function validate_and_normalize_ip() in /crits/ips/handlers.py.  Before the change in vocabulary  Both the IP "Type" and Indicator Type for IPv4 addresses was "Address - ipv4-addr".  Now, it looks like the IP4 "Type" for both indicators and ip's is "IPv4 Address".

**Comment by mgoffin** [comment]
Looks about right! When I get back I'll fix that function up. We will need to make adjustments since the SUBNET vocab might require different logic as well (they are also used for CIDR).

**Comment by packet-rat** [comment]
Mike,

Just realized this deprecates the current CRITs API STIX Data Output format option. 😩

This feature has been extremely useful in many use cases where a full blown TAXII Service is not required/desired. Any thoughts on how this functionality could be re-established (where would be the right place to extend the API: TAXII Services?)

Patrick Maroney
Cell: (609)841-5104


On Jun 29, 2015, at 5:33 PM, Mike Goffin <notifications@github.com> wrote:

This PR removes CybOX/STIX as requirements for core. This has a lot of fallout which resulted in the following major changes:

New vocabulary directory with custom CRITs vocabulary (some of it is similar to or the same as what was used with the standards because the values made sense, but we are considering them de-coupled from the standard and thus can be modified as the community sees fit).
These vocabularies are built on classes so there's no database lookups for these. Extending the vocabulary is as simple as adding attributes to a class and handling merge conflicts (however it's highly recommended you just open an issue for the new vocabulary value you wish to add so it can be discussed and added normally if it makes sense).
* Downloading TLOs are back to JSON instead of STIX.
* STIX Import is gone
If you wish to upload a file as an Object, you can use the new "File Upload" Object type.
If an Object cannot be made into an Indicator because its type isn't a valid Indicator type, the UI will tell you.
Indicators needed better context, so along with the new Indicator Type vocabulary they gained a "Threat Type" field, "Attack Type" field, and vocabulary for each.
* The "Standards API" is gone.
The "Objects" and "Relationships" POST APIs are gone as they are no longer based on database entries.
To compensate, forge_relationship and add_object were exposed to the API as PATCH requests and Updating through the API is now documented.
forge_relationship and add_object handlers have changes in arguments.

These features have been moved over to the TAXII service. Support for CybOX/STIX will stay in the TAXII service itself as the best and primary use of the standards for CRITs is through sharing which is what the TAXII service is for.
In order to properly use this PR you'll also need to use the "add_cybox_stix" branch of crits_services which will also have its own PR..

You can view, comment on, or merge this pull request online at:

  https://github.com/crits/crits/pull/523

Commit Summary

Removing CybOX/STIX from core (first stab).
Merge branch 'master' into remove_cybox_stix
Start of vocabulary.
Setup Event Type vocabulary.
Building out more vocabulary.
Start to implement RelationshipTypes vocab.
Merge branch 'master' into remove_cybox_stix
Commit forge_relationship and fix more dialogs.
Add in Indicator and Object support.
Expose "add_object" handler to the Updating API.
Hook up Indicator threat type and attack type.
Some cleanup and documentation changes.
Add Threat Type and Attack Type to Indicator stuffs.
Note new columns for threat and attack type.
Documenting API Updating via PATCH.
File Changes

M DEPENDENCIES (8)
M crits/actors/actor.py (124)
M crits/actors/handlers.py (27)
M crits/backdoors/handlers.py (4)
M crits/certificates/certificate.py (61)
M crits/certificates/handlers.py (5)
M crits/config/templates/config.html (7)
M crits/core/api.py (84)
M crits/core/class_mapper.py (50)
M crits/core/crits_mongoengine.py (265)
M crits/core/data_tools.py (5)
M crits/core/forms.py (4)
M crits/core/handlers.py (183)
D crits/core/management/commands/create_actors_content.py (62)
M crits/core/management/commands/create_default_collections.py (17)
D crits/core/management/commands/create_event_types.py (59)
D crits/core/management/commands/create_object_types.py (214)
D crits/core/management/commands/create_relationship_types.py (107)
D crits/core/management/commands/create_sectors.py (56)
M crits/core/management/commands/test_install.py (2)
M crits/core/sector.py (19)
M crits/core/static/js/dialogs.js (17)
M crits/core/templates/base.html (19)
M crits/core/templates/dialogs/indicator-blob.html (2)
M crits/core/templates/dialogs/new-indicator-csv.html (2)
D crits/core/templates/dialogs/new-standards.html (11)
M crits/core/templates/item_editor.html (14)
M crits/core/templatetags/filters.py (18)
M crits/core/views.py (37)
M crits/domains/domain.py (40)
M crits/domains/forms.py (10)
M crits/domains/handlers.py (13)
M crits/domains/views.py (11)
M crits/emails/email.py (97)
M crits/emails/handlers.py (28)
M crits/emails/static/js/emails.js (11)
M crits/emails/templates/email_detail.html (5)
M crits/emails/urls.py (1)
M crits/emails/views.py (23)
M crits/events/api.py (7)
M crits/events/event.py (95)
M crits/events/forms.py (11)
M crits/events/handlers.py (20)
M crits/events/static/js/events.js (3)
M crits/events/views.py (30)
M crits/indicators/api.py (4)
M crits/indicators/forms.py (37)
M crits/indicators/handlers.py (149)
M crits/indicators/indicator.py (108)
M crits/indicators/static/js/indicators.js (142)
M crits/indicators/templates/indicator_detail.html (38)
M crits/indicators/urls.py (3)
M crits/indicators/views.py (207)
M crits/ips/forms.py (7)
M crits/ips/handlers.py (8)
M crits/ips/ip.py (63)
M crits/notifications/processor.py (4)
D crits/objects/api.py (106)
M crits/objects/forms.py (53)
M crits/objects/handlers.py (178)
D crits/objects/object_mapper.py (519)
D crits/objects/object_type.py (39)
M crits/objects/static/js/objects.js (84)
M crits/objects/templates/objects_listing_row_widget.html (16)
M crits/objects/templates/objects_listing_widget.html (2)
M crits/objects/views.py (77)
M crits/pcaps/handlers.py (5)
M crits/pcaps/pcap.py (50)
M crits/raw_data/raw_data.py (34)
D crits/relationships/api.py (98)
M crits/relationships/forms.py (11)
M crits/relationships/handlers.py (76)
M crits/relationships/tests.py (4)
M crits/relationships/views.py (20)
M crits/samples/handlers.py (12)
M crits/samples/migrate.py (6)
M crits/samples/sample.py (83)
M crits/samples/views.py (8)
M crits/settings.py (13)
D crits/standards/api.py (107)
D crits/standards/forms.py (24)
D crits/standards/handlers.py (56)
D crits/standards/parsers.py (515)
D crits/standards/templates/import_results.html (45)
D crits/standards/urls.py (5)
D crits/standards/views.py (65)
M crits/urls.py (7)
R crits/vocabulary/__init__.py (0)
A crits/vocabulary/actors.py (89)
A crits/vocabulary/confidence.py (11)
A crits/vocabulary/events.py (25)
A crits/vocabulary/indicators.py (172)
A crits/vocabulary/ips.py (12)
A crits/vocabulary/kill_chain.py (15)
A crits/vocabulary/objects.py (114)
A crits/vocabulary/relationships.py (136)
A crits/vocabulary/sectors.py (24)
A crits/vocabulary/status.py (12)
A crits/vocabulary/vocab.py (25)
M documentation/help_main.html (220)
M documentation/help_main.txt (129)
M documentation/src/crits.objects.rst (15)
M documentation/src/crits.rst (1)
D documentation/src/crits.standards.rst (46)
M extras/www/static/js/dialogs.js (17)
M extras/www/static/js/emails.js (11)
M extras/www/static/js/events.js (3)
M extras/www/static/js/indicators.js (142)
M extras/www/static/js/objects.js (84)
M requirements.txt (2)
M salt/roots/salt/python_requirements.sls (12)
Patch Links:

https://github.com/crits/crits/pull/523.patch
https://github.com/crits/crits/pull/523.diff

**Comment by mgoffin** [comment]
The API now exists with the TAXII Service for importing documents but we won't be supporting adding a STIX format to all TLOs in core.

I don't think it's possible to add a format through service API extensions but if someone can find a way to do it via the TAXII service that would be the place to do it.

**Comment by mgoffin** [comment]
@DukeOfHazard I think the IP stuff should be fixed. Can you confirm?

**Comment by DukeOfHazard** [comment]
@mgoffin Yes, it appears to be resolved.  Thank you!

**Comment by mgoffin** [comment]
If there's no other feedback, we'll pull this into master and see what sort of other fallout happens with more exposure.

**Pull request merged**
