### PR TITLE
mongoengine 0.9.0 support added

### PR DESCRIPTION
**Pull request by frbapolkosnik**
Update to use mongoengine0.9.0

### CODE REVIEW

**Comment by frbapolkosnik** [comment]
I think that it is good to go.

**Comment by brlogan** [comment]
Should probably update version in DEPENDENCIES too.

**Comment by mgoffin** [comment]
Yea, I just pulled that PR in (thanks for the reminder). DEPENDENCIES and requirements should be kept in-line.

**Comment by frbapolkosnik** [comment]
Updated DEPENDENCIES, good to go.

**Pull request merged**
