### PR TITLE
Sharing String Indicators and Relationships via STIX

### PR DESCRIPTION
**Pull request by brlogan**
This PR is an attempt at enabling the sharing of String Indicators and TLO relationships via STIX.

Strings:
- There is no CybOX object type designed for generic strings
- This solution uses the CybOX Custom object
  - Object custom_name = "crits:String"
  - The single custom_property name is "value"
  - This requires an update to cybox-2.1.0.11 and stix-1.1.1.5
  - This is intended to address #442

Relationships:
- In order to describe via STIX the inter-object relationships, all Observables are wrapped within a STIX Indicator (I'm not a huge fan of this Observable wrapping and I expect @mgoffin won't be either, so I'm open to suggestions :smiley:)
  - The STIX Indicator title and description indicate that the Indicator is simply a wrapper
  - The STIX Indicator's related_indicators attribute describes the relationships using references to other STIX Indicators
  - We could only wrap those Observables that actually have relationships, but I thought it might be better to consistently wrap all of them
- Email attachments are automatically included with an Email
  - The Sample is added as its own Indicator-wrapped Observable
  - The Sample is referenced in the "attachments" attribute of the Email
  - The relationship between the Email and the Sample is documented in the related_indicators attribute of their respective Indicator wrapper
  - This attempts to address #437 
- In order to describe via STIX the Event -> Object relationships, an Incident is added to the STIX output. (I'm not a huge fan of this either, so again, I'm open to suggestions)
  - Relationships to Indicators and Indicator-wrapped Observables are listed in the Incident's related_indicators attribute.
  - Any objects for which a relationship to the Event is not defined are assigned a "Related_To" relationship.

### CODE REVIEW

**Comment by mgoffin** [comment]
Partial aside to this, but the custom "crits:Foo" object...how hard was it to implement? As in, if it was simplistic to replicate can we "backfill" support for the rest of the indicator types into STIX/CybOX that we don't have great support for? Would also pave the way for supporting a larger vocabulary instead of waiting for CybOX to implement things?

**Comment by brlogan** [comment]
It's very simple to implement. You instantiate the Custom object, set a name and description, then add any custom properties you need. For the case of Indicators, the only property would probably be "value".
It shouldn't take too much work to build out any types that aren't currently supported by python-cybox.

**Comment by mgoffin** [comment]
So in the future if we wanted to expand on Indicators (add fields, alter vocabulary, etc.) we can change the object_mapper to be amazingly simple (at least in the CRITs -> CybOX direction):

- Create custom object
- Jam in attributes

And we could do this for every single Indicator type CRITs supports? What sort of custom code would be required to know how to parse out our custom object on the other end (if someone wasn't using CRITs to parse the STIX document)?

**Comment by brlogan** [comment]
It probably makes sense to use the standard types in python-cybox wherever possible for optimal interoperability, but I don't see why we couldn't use the Custom object for everything else. It would be very useful for CRITs <-> CRITs sharing while still being valid CybOX. Indicator types whose values aren't just strings may be somewhat more complex, but there aren't many of those.

As for parsing the Custom object from STIX, it would of course depend on the use case, but they could grab any number of properties with something like this:
```python
if isinstance(cybox_obj, Custom):
    properties = {}
    object_name = cybox_obj.custom_name
    for prop in cybox_obj.custom_properties:
        properties[prop.name] = prop.value
```

**Comment by mgoffin** [comment]
Cool. So it would be 10000x easier to do CRITs->CRITs STIX sharing, but when it comes to consuming STIX generated by other sources, all bets are off.

**Comment by brlogan** [comment]
Pretty much.
I don't think it would be a good idea to solely use the Custom object for everything, but I think it could be a good solution for those types that aren't currently supported in python-cybox. CRITs instances would be able to consume the Custom objects correctly, and because the Custom objects are valid CybOX, the worst that *should* happen with other STIX-consuming systems is that those objects just get dropped.

**Comment by mgoffin** [comment]
Which version of CybOX does this require? In trying to use this PR I am getting a traceback because:

```python
    from cybox.objects.custom_object import Custom
ImportError: No module named custom_object
```

If it requires a new version we should put that in requirements.txt as well as make an UPDATING entry.

**Comment by gtback** [comment]
The custom object was added in 2.1.0.10: 
https://github.com/CybOXProject/python-cybox/releases/tag/v2.1.0.10

The latest version is 2.1.0.11

**Comment by mgoffin** [comment]
Yea then if that and whatever STIX version is required both work with CRITs then UPDATING should get an entry to install the right versions and requirements.txt should get the changes as well.

**Comment by brlogan** [comment]
Darn it, I can't believe I forgot to even mention that. Both STIX and TAXII should be updated for this to work. I won't have access to my DEV laptop until Monday night, but I'll see if I can add in those updates before then.

**Comment by mgoffin** [comment]
I tried this out. Got this with an Indicator of type "String":

```
Imported
Event	554d4f8303b6e0145efdb0e2
Failed
Custom	ID: example:Custom-ddb9cb3d-76f1-426c-a8b7-0513ae4e1ec5

Can't create indicator with an empty type field
```

This is pulled from the STIX doc I tried to upload:

```xml
    <stix:Indicators>
        <stix:Indicator id="example:indicator-e2d11d22-5698-4154-8fd0-ce4d7edc2cdd" timestamp="2015-05-09T00:06:05.269136+00:00" xsi:type='indicator:IndicatorType'>
            <indicator:Observable id="example:Observable-bb34dd7e-b48c-402f-b1f8-a891b1fff78e">
                <cybox:Object id="example:Custom-ddb9cb3d-76f1-426c-a8b7-0513ae4e1ec5">
                    <cybox:Properties xsi:type="CustomObj:CustomObjectType" custom_name="crits:String">
                        <cyboxCommon:Custom_Properties>
                            <cyboxCommon:Property name="value" description="Generic String">this is an indicator</cyboxCommon:Property>
                        </cyboxCommon:Custom_Properties>
                        <CustomObj:Description>This is a generic string used as the value of an Indicator or Object within CRITs.</CustomObj:Description>
                    </cybox:Properties>
                </cybox:Object>
            </indicator:Observable>
            <indicator:Producer>
                <stixCommon:Identity>
                    <stixCommon:Name>Home</stixCommon:Name>
                </stixCommon:Identity>
            </indicator:Producer>
        </stix:Indicator>
    </stix:Indicators>
```

**Comment by mgoffin** [comment]
@brlogan Any ideas on the above problem?

**Comment by brlogan** [comment]
Sorry for the delay and the trouble. I was out Thursday-Monday.

It looks like I missed a couple function calls when merging Master. It should work now.

**Pull request merged**
