### PR TITLE
New Signature TLO

### PR DESCRIPTION
**Pull request by dreardon**
This PR should address all the changes that were discussed in CRITs request https://github.com/crits/crits/issues/625. The features include:
 - A new TLO for Signatures which was modeled after the Raw Data TLO
 - New meta-data for Tool Type, Min/Max Versions of the tool, and Tool Dependencies
 - Tool Dependencies are a type-ahead list of values, but still allows new entries (similar to Buckets)
 - Instance-specific list of available Signature Tools defined by the admin (Bro, Snort, and Yara added by default)

After this is worked out and accepted, there are plans to add new services which will take advantage of this new TLO. Updates could also be made to existing services to take advantage of this TLO, but those could be discussed after we have this as part of the baseline.

Thank you very much.

### CODE REVIEW

**Comment by dreardon** [comment]
Good point about better emphasizing the signature itself. I didn't want the "weight" of the line by line commenting and highlighting of the raw data "data" component for this purpose, but I think I might have gone too far in the other direction of just making it another data element on the page and it blends in. I'll see what I can do.

**Comment by mgoffin** [comment]
Yea I agree that removing the raw data view was a good idea. It would be overkill for sure. Thanks for looking into this :) After that, if everything works in the UI and the code looks solid, I suspect we'll get this accepted asap!

**Comment by dreardon** [comment]
Thank you both for the quick feedback. I made some adjustments based on your input and added them to this PR (see above). Please let me know if you notice anything else. Thank you again.

**Comment by mgoffin** [comment]
I suspect you are using the diffing piece wrong. You need to select TWO things to diff. You are most likely only selecting one thing and assuming it's diffing against the one you are viewing, which is incorrect.

**Comment by mgoffin** [comment]
I think this looks good! I'm going to accept it into master and make one quick change after. Since there's no real difference between the `Data` section where the signature is displayed and the contents of the `Signature` tab, we might as well remove the `Signature` tab and make some room for potential services. Once it's in master we can get a lot of eyes on it and get some more testing in to polish stuff up.

Thanks for doing this! I can see this being amazingly useful and once services are written for them it will really change things for a lot of people!

**Comment by armtash** [comment]
Have you considered adding an "Activity" section to the Signatures TLO similar to how one exists for Indicators?  It would be a nice addition so that one can track hits of different signatures.

**Pull request merged**
